<?php /** @var $app \H4D\Leveret\Application */;?>
<h1>General information</h1>

<h2>Application info</h2>
<dl>
    <dt>Name</dt><dd><?php echo $app->getName();?></dd>
    <dt>Environment</dt><dd><?php echo $app->getEnvironment();?></dd>
    <dt>Config file</dt><dd><?php echo $app->getConfig()->getConfigFilePath();?></dd>
</dl>

<h2>System info</h2>
<dl>
    <dt>Host</dt><dd><?php echo $app->getRequest()->getHttpHost();?></dd>
</dl>

<h2>PHP info</h2>
<dl>
    <dt>PHP version</dt><dd><?php echo phpversion();?></dd>
</dl>
